# Generated by Django 5.1.7 on 2026-05-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_alternativa_id_alter_documento_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={'ordering': ['nombre'], 'verbose_name': 'Medida de desempeño (MOP)', 'verbose_name_plural': 'Medidas de desempeño (MOP)'},
        ),
        migrations.AddField(
            model_name='alternativa',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='alternativas/anexos/'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alternativas/fotos/'),
        ),
    ]
