# Generated by Django 5.1.7 on 2026-05-21 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dimension_options_alternativa_anexo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='api.alternativa')),
            ],
            options={
                'verbose_name': 'Capacidad',
                'verbose_name_plural': 'Capacidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.CharField(blank=True, max_length=64)),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('entero', 'Entero'), ('fecha', 'Fecha'), ('booleano', 'Sí/No'), ('porcentaje', 'Porcentaje')], default='texto', max_length=20)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='api.alternativa')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
                'ordering': ['id'],
            },
        ),
    ]
