# Generated by Django 5.1.7 on 2026-05-22 13:20

import api.upload_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_capacidad_caracteristica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='anexo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=api.upload_utils.alternativa_anexo_upload),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=api.upload_utils.alternativa_foto_upload),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(max_length=500, upload_to=api.upload_utils.documento_upload),
        ),
        migrations.AlterField(
            model_name='documentocriterio',
            name='archivo',
            field=models.FileField(max_length=500, upload_to=api.upload_utils.documento_criterio_upload),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=api.upload_utils.proyecto_foto_upload),
        ),
    ]
