# Generated by Django 5.1.7 on 2026-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_file_field_max_length_and_upload_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='referencia',
            field=models.TextField(blank=True),
        ),
    ]
