# Generated by Django 5.1.7 on 2026-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alternativa_optional_text_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristica',
            name='tipo_dato',
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='dato',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
