# Generated by Django 5.1.7 on 2026-05-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_caracteristica_tipo_dato_to_dato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristica',
            name='unidad',
        ),
    ]
