# Generated by Django 5.1.7 on 2026-05-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_caracteristica_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='costo_unidad',
            field=models.CharField(choices=[('MUSD', 'MUSD (millones USD)'), ('USD', 'USD'), ('COP', 'COP'), ('MEUR', 'MEUR (millones EUR)'), ('EUR', 'EUR'), ('MGBP', 'MGBP (millones GBP)'), ('GBP', 'GBP')], default='MUSD', max_length=8),
        ),
    ]
