# Generated by Django 5.1.7 on 2026-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alternativa_costo_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='autonomia',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='desplazamiento',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='eslora_maxima',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='laboratorios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='otras_caracteristicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='posicionamiento_dinamico',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='propulsion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tripulacion',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='velocidad_crucero',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='velocidad_maxima',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
