# Generated by Django 5.1.7 on 2026-05-22 16:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_proyecto_caracteristicas_generales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='api.proyecto')),
            ],
            options={
                'verbose_name': 'Escenario',
                'verbose_name_plural': 'Escenarios',
                'ordering': ['orden', 'nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PesoEscenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('atributo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesos_escenario', to='api.atributo')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesos_escenario', to='api.dimension')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='api.escenario')),
                ('subatributo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesos_escenario', to='api.subatributo')),
            ],
            options={
                'verbose_name': 'Peso por escenario',
                'verbose_name_plural': 'Pesos por escenario',
            },
        ),
        migrations.AddConstraint(
            model_name='escenario',
            constraint=models.UniqueConstraint(fields=('proyecto', 'nombre'), name='uniq_escenario_proyecto_nombre'),
        ),
        migrations.AddConstraint(
            model_name='pesoescenario',
            constraint=models.UniqueConstraint(condition=models.Q(('dimension__isnull', False)), fields=('escenario', 'dimension'), name='uniq_peso_escenario_dimension'),
        ),
        migrations.AddConstraint(
            model_name='pesoescenario',
            constraint=models.UniqueConstraint(condition=models.Q(('atributo__isnull', False)), fields=('escenario', 'atributo'), name='uniq_peso_escenario_atributo'),
        ),
        migrations.AddConstraint(
            model_name='pesoescenario',
            constraint=models.UniqueConstraint(condition=models.Q(('subatributo__isnull', False)), fields=('escenario', 'subatributo'), name='uniq_peso_escenario_subatributo'),
        ),
    ]
