# Generated by Django 5.1.7 on 2026-05-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_escenario_peso_escenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('referencia', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='api.proyecto')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dimension',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='api.categoria'),
        ),
        migrations.AddField(
            model_name='pesoescenario',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesos_escenario', to='api.categoria'),
        ),
        migrations.AddConstraint(
            model_name='pesoescenario',
            constraint=models.UniqueConstraint(condition=models.Q(('categoria__isnull', False)), fields=('escenario', 'categoria'), name='uniq_peso_escenario_categoria'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('proyecto', 'nombre'), name='uniq_categoria_proyecto_nombre'),
        ),
    ]
