# Generated by Django 6.0.5 on 2026-06-11 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_omoe_arbol_criterios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluadorMision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asignación evaluador → misión',
                'verbose_name_plural': 'Asignaciones evaluador → misión',
            },
        ),
        migrations.CreateModel(
            name='OfertanteAlternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asignación ofertante → alternativa',
                'verbose_name_plural': 'Asignaciones ofertante → alternativa',
            },
        ),
        migrations.CreateModel(
            name='ProyectoMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('jefe', 'Jefe / corresponsable'), ('analista', 'Analista interno'), ('evaluador', 'Evaluador / experto'), ('ofertante', 'Ofertante / proveedor'), ('auditor', 'Auditor (solo lectura)')], max_length=16)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membresía de proyecto',
                'verbose_name_plural': 'Membresías de proyecto',
                'ordering': ['proyecto_id', 'usuario_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='categoria',
            name='uniq_categoria_proyecto_nombre',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='categoria',
        ),
        migrations.RemoveConstraint(
            model_name='pesoescenario',
            name='uniq_peso_escenario_categoria',
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='capacidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='caracteristicaplantilla',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentocriterio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dpcriterio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='escenario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grupoafinidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mopcriterio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='omoe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pesoescenario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subatributo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vopresultado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='evaluadormision',
            name='mision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluadores_asignados', to='api.mision'),
        ),
        migrations.AddField(
            model_name='ofertantealternativa',
            name='alternativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertantes_asignados', to='api.alternativa'),
        ),
        migrations.AddField(
            model_name='proyectomembership',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.proyecto'),
        ),
        migrations.AddField(
            model_name='proyectomembership',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ofertantealternativa',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas_asignadas', to='api.proyectomembership'),
        ),
        migrations.AddField(
            model_name='evaluadormision',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones_asignadas', to='api.proyectomembership'),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='pesoescenario',
            name='categoria',
        ),
        migrations.AddConstraint(
            model_name='proyectomembership',
            constraint=models.UniqueConstraint(fields=('proyecto', 'usuario'), name='uniq_proyecto_usuario_membership'),
        ),
        migrations.AddConstraint(
            model_name='ofertantealternativa',
            constraint=models.UniqueConstraint(fields=('membership', 'alternativa'), name='uniq_ofertante_alternativa'),
        ),
        migrations.AddConstraint(
            model_name='evaluadormision',
            constraint=models.UniqueConstraint(fields=('membership', 'mision'), name='uniq_evaluador_mision'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
