# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alternativa_apodo_max_8'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesoGrupoAhp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('manual', 'Manual'), ('ahp', 'AHP')], default='manual', max_length=8)),
                ('juicios', models.JSONField(blank=True, default=dict)),
                ('pesos_calculados', models.JSONField(blank=True, default=dict)),
                ('consistency_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('lambda_max', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peso_grupos_ahp', to='api.escenario')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peso_grupos_ahp_hijos', to='api.nodoarbol')),
            ],
            options={
                'verbose_name': 'Peso grupo AHP',
                'verbose_name_plural': 'Pesos grupo AHP',
            },
        ),
        migrations.AddConstraint(
            model_name='pesogrupoahp',
            constraint=models.UniqueConstraint(fields=('escenario', 'parent'), name='uniq_peso_grupo_ahp_esc_parent'),
        ),
    ]
